#index:
#    path: /
#    controller: App\Controller\DefaultController::index
products_all_show:
    path: /api/products
    controller: App\Controller\ProductController::showAllProducts
    methods: GET
products_one_show:
    path: /api/products/{id}
    controller: App\Controller\ProductController::showOneProducts
    methods: GET
products_create:
    path: /api/products
    controller: App\Controller\ProductController::createProducts
    methods: POST
products_update:
    path: /api/products/{id}
    controller: App\Controller\ProductController::updateProducts
    methods: PUT
products_delete:
    path: /api/products/{id}
    controller: App\Controller\ProductController::deleteProducts
    methods: DELETE
